[features]
resolution = true
skip-lint = false

[programs.devnet]
question_bank = "CSRftWGDWFCbwvib9s6XbnqJheuSR5eVPmieKGDJmA7Y"
tournament_manager = "DE58k65KchHuDCABYARfGP5Jc1p14yRrx1UayweapYx9"
reward_distributor = "EDy3LJ7eDf8UbpdsikwejxEDPxk48spTG3rwdzuM5TFd"

[programs.mainnet-beta]
question_bank = "CSRftWGDWFCbwvib9s6XbnqJheuSR5eVPmieKGDJmA7Y"
tournament_manager = "DE58k65KchHuDCABYARfGP5Jc1p14yRrx1UayweapYx9"
reward_distributor = "EDy3LJ7eDf8UbpdsikwejxEDPxk48spTG3rwdzuM5TFd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/question_bank",
    "programs/tournament_manager", 
    "programs/reward_distributor"
]

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "metadata_program.so"

[[test.genesis]]
address = "hadeK9DLv9eA7ya5KCTqSvSvRZeJC3JgD5a9Y3CNbvu"
program = "hadeswap_program.so"

[test.validator]
url = "https://api.devnet.solana.com"
commitment = "processed"